### PR TITLE
Feature: adding the ability to manually register modules

### PR DESCRIPTION
**Pull request by wovalle**
This pr kind of solves https://github.com/alveflo/tsmediator/issues/12.

Didn't want to touch the tests pipeline in this PR but I had to :(

Note: noticed that the linter is not working properly.

### CODE REVIEW

**Comment by alveflo** [comment]
Looks good to me, nice job! 👍 

Don't worry about the tests pipeline, it obviously had to be fixed sooner or later anyway 😄  

I'll release this asap!

**Comment by alveflo** [comment]
@wovalle so I was just about to release this and realized that we need some basic documentation about how to register a handler.

Are you interested in writing a couple of lines? Otherwise I'll do it as soon as possible

**Comment by wovalle** [comment]
@alveflo Hey, I might do it this weekend, have a busy week :)

**Comment by alveflo** [comment]
@wovalle yeah me too haha... no stress, do it when you've got time for it

**Comment by alveflo** [comment]
@wovalle I added some very basic description of this to the readme, so you don't need to worry about that. Feel free to add some description though if you think it's needed 😄

**Comment by alveflo** [comment]
this feature is now also deployed to npm fyi

**Pull request merged**
